version: '3'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=social_network
    container_name: postgres
    ports:
      - "5432:5432"
    command: postgres -N 1000

